<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_length" value="0.44"/>
    <xacro:property name="chassis_height" value="0.2"/>
    <xacro:property name="chassis_mass" value="2.0"/>
    <xacro:property name="wheel_radius" value="0.075"/>
    <xacro:property name="wheel_thickness" value="0.05"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.02"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="connector_size" value="0.02"/>
    <xacro:property name="connector_height" value="0.055"/>
    <xacro:property name="connector_offset_z" value="-0.02"/>
    <xacro:property name="caster_wheel_offset_x" value="0.1"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius + 0.0115}"/>
    
    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 ${chassis_height/2}"/>
            <geometry>
                <cylinder radius="${chassis_length/2}" length="${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${chassis_height/2}"/>
            <geometry>
                <cylinder radius="${chassis_length/2}" length="${chassis_height}"/>
            </geometry>
        </collision>
         <xacro:inertial_cylinder mass="0.5" length="${chassis_height}" radius="${chassis_length/2}">
            <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>




    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- CASTER FRONT WHEEL LINK -->

    <joint name="front_connector_joint" type="fixed">
        <parent link="chassis"/>
        <child link="front_connector"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${connector_offset_z}" rpy="0 0 0" />
    </joint>

    <link name="front_connector">
        <visual>
            <origin xyz="${caster_wheel_offset_x} 0 0"/>
            <geometry>
                <box size="${connector_size} ${connector_size} ${connector_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${caster_wheel_offset_x} 0 0"/>
            <geometry>
                <box size="${connector_size} ${connector_size} ${connector_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="${connector_size}" y="${connector_size}" z="${connector_height}">
            <origin xyz="${caster_wheel_offset_x} 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="front_connector">
        <material>Gazebo/Orange</material>
    </gazebo>

    <joint name="caster_front_wheel_joint" type="fixed">
        <parent link="front_connector"/>
        <child link="caster_front_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_front_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_front_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    
    <!-- CASTER BACK WHEEL LINK -->

    <joint name="back_connector_joint" type="fixed">
        <parent link="chassis"/>
        <child link="back_connector"/>
        <origin xyz="${-caster_wheel_offset_x} 0 ${connector_offset_z}" rpy="0 0 0" />
    </joint>

    <link name="back_connector">
        <visual>
            <origin xyz="${-caster_wheel_offset_x} 0 0"/>
            <geometry>
                <box size="${connector_size} ${connector_size} ${connector_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${-caster_wheel_offset_x} 0 0"/>
            <geometry>
                <box size="${connector_size} ${connector_size} ${connector_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="${connector_size}" y="${connector_size}" z="${connector_height}">
            <origin xyz="${-caster_wheel_offset_x} 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="back_connector">
        <material>Gazebo/Orange</material>
    </gazebo>

    <joint name="caster_back_wheel_joint" type="fixed">
        <parent link="back_connector"/>
        <child link="caster_back_wheel"/>
        <origin xyz="${-caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_back_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_back_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
</robot>