<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <joint name="ultrasonic_sensor_joint" type="fixed">
        <parent link="chassis"/>
        <child link="ultrasonic_frame"/>
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
    </joint>

    <link name="ultrasonic_frame">
        <!-- Rectangular Base -->
        <visual>
            <geometry>
                <box size="0.005 0.04 0.02"/>
            </geometry>
            <origin xyz="0 0 -0.0025" rpy="0 0 0"/>
        </visual>
        

        <collision>
            <geometry>
                <box size="0.005 0.04 0.02"/>
            </geometry>
            <origin xyz="0 0 -0.0025" rpy="0 0 0"/>
        </collision>

        <xacro:inertial_cylinder mass="0.1" length="0.02" radius="0.01">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="ultrasonic_frame">
        <material>Gazebo/Red</material>
        <sensor type="ray" name="range_sensor">
            <visualize>true</visualize>
            <pose> 0 0 0 0 0 0 </pose>
            <ray>
                <scan>
                    <horizontal>
                        <samples>10</samples>
                        <resolution>1</resolution>
                        <min_angle>-0.087</min_angle>
                        <max_angle>0.087</max_angle>
                    </horizontal>
                    <!-- <vertical>
                        <samples>10</samples>
                        <resolution>1</resolution>
                        <min_angle>-0.087</min_angle>
                        <max_angle>0.087</max_angle>
                    </vertical> -->
                </scan>
                <range>
                    <min>0.10</min>
                    <max>5.0</max>
                    <resolution>0.01</resolution>
                    
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <update_rate>30</update_rate>
            <plugin name="gazebo_ros_range_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <remapping>~/out:=range</remapping>
                </ros>
                <output_type>sensor_msgs/Range</output_type>
                <frame_name>ultrasonic_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>
</robot>
