joy_node:
    ros__parameters:
        device_id: 0
        deadzone: 0.05
        autorepeat_rate: 20.0

teleop_node:
    ros__parameters:
        axis_linear:  # Left thumb stick vertical
            x: 1
        scale_linear:
            x: 1.0 #0.7
        scale_linear_turbo:
            x: 2.0 #1.5

        axis_angular:  # Left thumb stick horizontal
            yaw: 0
        scale_angular:
            yaw: 1.2 # 0.4
        scale_angular_turbo:
            x: 1.8 #1.5

        enable_button: 7  # Left trigger button
        enable_turbo_button: 9  # Right trigger button