person_follower_hc:
  ros__parameters:
    cascade_path: "$(find-package-share vedita_bot)/models/haarcascade_frontalface_default.xml"
    scale_factor: 1.1
    min_neighbors: 5
    min_size: [40, 40]
    linear_speed: 0.2
    angular_gain: 0.005
    detection_threshold: 150

person_follower_yolo:
  ros__parameters:
    model_path: "$(find-package-share vedita_bot)/models/yolov11n-face.pt"